//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U2X.Barbearia.Web.dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u2xMainEntities : DbContext
    {
        public u2xMainEntities()
            : base("name=u2xMainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tbl_servico> tbl_servico { get; set; }
        public virtual DbSet<tbl_registro> tbl_registro { get; set; }
        public virtual DbSet<vw_registro> vw_registro { get; set; }
    }
}
