//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U2X.Barbearia.Web.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_registro
    {
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idServico { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> idCriador { get; set; }
        public Nullable<bool> isCartao { get; set; }
    
        public virtual tbl_servico tbl_servico { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
