//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U2X.Barbearia.Web.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_servico()
        {
            this.tbl_registro = new HashSet<tbl_registro>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_registro> tbl_registro { get; set; }
    }
}
